spring:
  application:
    name: order-service

  cloud:
    vault:
      enabled: true
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: http                    # explicit HTTP
      authentication: TOKEN
      token: ${VAULT_TOKEN:myroot}
#      kv:
#        enabled: true
#        backend: ${VAULT_MOUNT_PATH:myapp/secret}   # correct mount
#        application-name: order-service/dev
#        default-context: ${VAULT_PATH:order-service}
#        profiles:
#          active: false
      connection-timeout: 5000
      read-timeout: 15000
      fail-fast: false                # don't fail if Vault unreachable locally
  config:
    import: "optional:vault://${VAULT_PATH:myapp/secret/order-service/dev}"      # optional so local dev works without Vault

server:
  port: 8080

app:
  environment: ${APP_ENV:local}
  mainframe:
    host: ${MAINFRAME_HOST:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

datasource:
  url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:orderdb}
  username: ${DB_USERNAME:orderuser}
  password: ${DB_PASSWORD}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.boot.context.config: TRACE
    org.springframework.cloud.vault: TRACE
    org.springframework.vault: TRACE
  pattern:
    console: '{"timestamp":"%d","level":"%-5p","service":"${spring.application.name}","message":"%m"}%n'