app:
  replicas: 1
  tag: latest
  team: payments-team
config:
  logLevel: DEBUG
  appEnv: dev
  mqHost: mq-dev.internal
  kafkaBootstrapServers: kafka-dev:9092
  mainframeHost: mainframe-dev.internal

#vault:
#  path: order-service/dev
#  refreshInterval: 1h

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m