# platform-charts/order-service/templates/vaulttokensecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-vault-token
  labels:
    app: {{ .Values.app.name }}
type: Opaque
stringData:
  VAULT_TOKEN: {{ .Values.vault.token }}